# Generated by Django 4.2.3 on 2023-07-22 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=190)),
                ("price", models.DecimalField(decimal_places=2, max_digits=11)),
                ("description", models.CharField(max_length=255)),
                ("stock", models.IntegerField(default=1)),
                ("discount", models.IntegerField(default=0)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="products", to="products.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.CharField(max_length=255)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_product",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "image_product",
            },
        ),
    ]
