# Generated by Django 4.2.3 on 2023-07-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="categories",
        ),
        migrations.AddField(
            model_name="category",
            name="product",
            field=models.ManyToManyField(related_name="product", to="products.product"),
        ),
    ]
