# Generated by Django 4.2.3 on 2023-07-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageproduct",
            name="image_url",
            field=models.CharField(
                default="https://res.cloudinary.com/dnkw0zu2x/image/upload/v1688328201/django_commerce/no-photo.png"
            ),
        ),
    ]
